version: 2.1
jobs:
  build:
    docker:
      - image: manjarolinux/build
    # machine:
    #       image: "ubuntu-2004:current"
    #       docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run: git checkout main

      - run: |
          sed -i 's/#Color/Color/g' /etc/pacman.conf
          sed -i 's/HoldPkg/#HoldPkg/g' /etc/pacman.conf
          sed -i 's/IgnorePkg/#IgnorePkg/g' /etc/pacman.conf
          cat /etc/pacman.conf

      - run: |
          pacman -Syu --noconfirm --color always
          pacman -Sy --noconfirm --color always --needed base-devel curl wget coreutils xterm git sudo yay asp bat socat colorgcc procps-ng nano nano-syntax-highlighting micro tree aria2 openssh man-db

      - run: whoami

      - run: |
            # Wheel group is the sudo group in Arch Linux
            useradd --create-home --groups wheel  user
            echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            chown -R user ..
      
      - run: sudo -u user yay -Sy --color always --noconfirm --builddir . --cleanafter paru-bin
      
      
      - run: |
          cat \<<EOF > build.sh
          #!/bin/bash
          
          rm -rf "mongodb" || echo 
          git clone "https://aur.archlinux.org/mongodb.git"
          cd "mongodb"

          paru -Ui --noconfirm --color always --nocleanafter --pgpfetch --noredownload 
          
          EOF
          
          chmod a+x build.sh

          sudo -E -u user ./build.sh


      - run:
          command: ls -lRh
          when: always
workflows:
  main:
    jobs:
      - build
