# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: | 
          sudo add-apt-repository ppa:flatpak/stable -y && sudo apt install flatpak -y
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - run: |
          cat <<EOF > flatpak.txt
          org.inkscape.Inkscape
          com.wps.Office
          com.obsproject.Studio
          com.github.PintaProject.Pinta
          com.visualstudio.code
          us.zoom.Zoom
          org.remmina.Remmina
          org.videolan.VLC
          org.gimp.GIMP
          com.yubico.yubioath
          com.xnview.XnViewMP
          org.wireshark.Wireshark
          com.poweriso.PowerISO
          com.getpostman.Postman
          org.neverball.Neverball
          com.github.reds.LogisimEvolution
          rest.insomnia.Insomnia
          in.srev.guiscrcpy
          io.github.shiftey.Desktop
          org.fontforge.FontForge
          org.gnome.eog
          org.flameshot.Flameshot
          org.gnome.FileRoller
          org.gnome.baobab
          com.jetbrains.CLion
          com.gitlab.davem.ClamTk
          org.audacityteam.Audacity
          cc.arduino.arduinoide
          com.github.tchx84.Flatseal
          com.belmoussaoui.Decoder
          com.belmoussaoui.Obfuscate
          com.belmoussaoui.Authenticator          
          EOF
          
          cat flatpak.txt 
          
          
      - run: |
          cat flatpak.txt | while read package 
          do
            flatpak install flathub "$package" -y
            echo ""
            echo ""
            echo "===================================================================================================="
            echo "===================================================================================================="
            echo ""
            echo ""
          done


      - run: flatpak list --show-details --verbose

      - run: |
          cat flatpak.txt | while read package 
          do
            flatpak info --show-permissions "$package"
            echo ""
            echo ""
            echo "===================================================================================================="
            echo "===================================================================================================="
            echo ""
            echo ""
          done
          
